[package]
name = "ck3-tiger"
version = "0.3.2"
edition = "2021"

[dependencies]
anyhow = "1"
bitflags = "1.3.2"
clap = { version = "3", features = ["derive"] }
encoding = "0.2"
fnv = "1"
home = "0.5"
image = "0.24"
itertools = "0.10"
lazy_static = "1"
png = "0.17.6"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1"
unicode-width = "0.1.9"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.10"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "criterion"
harness = false

[profile.bench]
debug = true
