[workspace]

members = [
    "ck3-tiger",
    ".",
]

[package]
name = "tiger-lib"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1"
as-any = "0.3.0"
bitflags = "1.3.2"
encoding = "0.2"
fnv = "1"
image = "0.24"
lazy_static = "1"
png = "0.17.6"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1"
unicode-width = "0.1.9"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.10"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "criterion"
harness = false

[profile.bench]
debug = true
