[package]
name = "ck3-tiger"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiger-lib = { path = ".." }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
home = "0.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.50"
ansi_term = "0.12.1"
