[package]
name = "ck3-tiger"
version = "0.7.2"
edition = "2021"
default-run = "ck3-tiger"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiger-lib = { path = "..", features = ["ck3"] }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
console = "0.15.7"

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12.1"
